require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ActivityScoresController do

  # This should return the minimal set of attributes required to create a valid
  # ActivityScore. As you add validations to ActivityScore, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "repo_id" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ActivityScoresController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all activity_scores as @activity_scores" do
      activity_score = ActivityScore.create! valid_attributes
      get :index, {}, valid_session
      assigns(:activity_scores).should eq([activity_score])
    end
  end

  describe "GET show" do
    it "assigns the requested activity_score as @activity_score" do
      activity_score = ActivityScore.create! valid_attributes
      get :show, {:id => activity_score.to_param}, valid_session
      assigns(:activity_score).should eq(activity_score)
    end
  end

  describe "GET new" do
    it "assigns a new activity_score as @activity_score" do
      get :new, {}, valid_session
      assigns(:activity_score).should be_a_new(ActivityScore)
    end
  end

  describe "GET edit" do
    it "assigns the requested activity_score as @activity_score" do
      activity_score = ActivityScore.create! valid_attributes
      get :edit, {:id => activity_score.to_param}, valid_session
      assigns(:activity_score).should eq(activity_score)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new ActivityScore" do
        expect {
          post :create, {:activity_score => valid_attributes}, valid_session
        }.to change(ActivityScore, :count).by(1)
      end

      it "assigns a newly created activity_score as @activity_score" do
        post :create, {:activity_score => valid_attributes}, valid_session
        assigns(:activity_score).should be_a(ActivityScore)
        assigns(:activity_score).should be_persisted
      end

      it "redirects to the created activity_score" do
        post :create, {:activity_score => valid_attributes}, valid_session
        response.should redirect_to(ActivityScore.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved activity_score as @activity_score" do
        # Trigger the behavior that occurs when invalid params are submitted
        ActivityScore.any_instance.stub(:save).and_return(false)
        post :create, {:activity_score => { "repo_id" => "invalid value" }}, valid_session
        assigns(:activity_score).should be_a_new(ActivityScore)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        ActivityScore.any_instance.stub(:save).and_return(false)
        post :create, {:activity_score => { "repo_id" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested activity_score" do
        activity_score = ActivityScore.create! valid_attributes
        # Assuming there are no other activity_scores in the database, this
        # specifies that the ActivityScore created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        ActivityScore.any_instance.should_receive(:update).with({ "repo_id" => "MyString" })
        put :update, {:id => activity_score.to_param, :activity_score => { "repo_id" => "MyString" }}, valid_session
      end

      it "assigns the requested activity_score as @activity_score" do
        activity_score = ActivityScore.create! valid_attributes
        put :update, {:id => activity_score.to_param, :activity_score => valid_attributes}, valid_session
        assigns(:activity_score).should eq(activity_score)
      end

      it "redirects to the activity_score" do
        activity_score = ActivityScore.create! valid_attributes
        put :update, {:id => activity_score.to_param, :activity_score => valid_attributes}, valid_session
        response.should redirect_to(activity_score)
      end
    end

    describe "with invalid params" do
      it "assigns the activity_score as @activity_score" do
        activity_score = ActivityScore.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ActivityScore.any_instance.stub(:save).and_return(false)
        put :update, {:id => activity_score.to_param, :activity_score => { "repo_id" => "invalid value" }}, valid_session
        assigns(:activity_score).should eq(activity_score)
      end

      it "re-renders the 'edit' template" do
        activity_score = ActivityScore.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ActivityScore.any_instance.stub(:save).and_return(false)
        put :update, {:id => activity_score.to_param, :activity_score => { "repo_id" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested activity_score" do
      activity_score = ActivityScore.create! valid_attributes
      expect {
        delete :destroy, {:id => activity_score.to_param}, valid_session
      }.to change(ActivityScore, :count).by(-1)
    end

    it "redirects to the activity_scores list" do
      activity_score = ActivityScore.create! valid_attributes
      delete :destroy, {:id => activity_score.to_param}, valid_session
      response.should redirect_to(activity_scores_url)
    end
  end

end
