require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ReposController do

  # This should return the minimal set of attributes required to create a valid
  # Repo. As you add validations to Repo, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "name" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ReposController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all repos as @repos" do
      repo = Repo.create! valid_attributes
      get :index, {}, valid_session
      assigns(:repos).should eq([repo])
    end
  end

  describe "GET show" do
    it "assigns the requested repo as @repo" do
      repo = Repo.create! valid_attributes
      get :show, {:id => repo.to_param}, valid_session
      assigns(:repo).should eq(repo)
    end
  end

  describe "GET new" do
    it "assigns a new repo as @repo" do
      get :new, {}, valid_session
      assigns(:repo).should be_a_new(Repo)
    end
  end

  describe "GET edit" do
    it "assigns the requested repo as @repo" do
      repo = Repo.create! valid_attributes
      get :edit, {:id => repo.to_param}, valid_session
      assigns(:repo).should eq(repo)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Repo" do
        expect {
          post :create, {:repo => valid_attributes}, valid_session
        }.to change(Repo, :count).by(1)
      end

      it "assigns a newly created repo as @repo" do
        post :create, {:repo => valid_attributes}, valid_session
        assigns(:repo).should be_a(Repo)
        assigns(:repo).should be_persisted
      end

      it "redirects to the created repo" do
        post :create, {:repo => valid_attributes}, valid_session
        response.should redirect_to(Repo.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved repo as @repo" do
        # Trigger the behavior that occurs when invalid params are submitted
        Repo.any_instance.stub(:save).and_return(false)
        post :create, {:repo => { "name" => "invalid value" }}, valid_session
        assigns(:repo).should be_a_new(Repo)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Repo.any_instance.stub(:save).and_return(false)
        post :create, {:repo => { "name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested repo" do
        repo = Repo.create! valid_attributes
        # Assuming there are no other repos in the database, this
        # specifies that the Repo created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Repo.any_instance.should_receive(:update).with({ "name" => "MyString" })
        put :update, {:id => repo.to_param, :repo => { "name" => "MyString" }}, valid_session
      end

      it "assigns the requested repo as @repo" do
        repo = Repo.create! valid_attributes
        put :update, {:id => repo.to_param, :repo => valid_attributes}, valid_session
        assigns(:repo).should eq(repo)
      end

      it "redirects to the repo" do
        repo = Repo.create! valid_attributes
        put :update, {:id => repo.to_param, :repo => valid_attributes}, valid_session
        response.should redirect_to(repo)
      end
    end

    describe "with invalid params" do
      it "assigns the repo as @repo" do
        repo = Repo.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Repo.any_instance.stub(:save).and_return(false)
        put :update, {:id => repo.to_param, :repo => { "name" => "invalid value" }}, valid_session
        assigns(:repo).should eq(repo)
      end

      it "re-renders the 'edit' template" do
        repo = Repo.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Repo.any_instance.stub(:save).and_return(false)
        put :update, {:id => repo.to_param, :repo => { "name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested repo" do
      repo = Repo.create! valid_attributes
      expect {
        delete :destroy, {:id => repo.to_param}, valid_session
      }.to change(Repo, :count).by(-1)
    end

    it "redirects to the repos list" do
      repo = Repo.create! valid_attributes
      delete :destroy, {:id => repo.to_param}, valid_session
      response.should redirect_to(repos_url)
    end
  end

end
